apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-willow-mde
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
    rbac.authorization.halo.run/aggregate-to-authenticated: "true"
rules:
  - nonResourceURLs: [ "/apis/api.willow.guqing.github.io/editor-options" ]
    verbs: [ "get" ]